# Generated by Django 5.0.8 on 2024-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='video',
            field=models.FileField(upload_to='media'),
        ),
    ]
