# Generated by Django 5.0.8 on 2024-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_memo_image_alter_memo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
